### ISSUE TITLE
Hook into hive

### ISSUE THREAD

**Issue by winwisely99** [AKushWarrior/autotrie#1]
Autotrie looks really useful for indexing text in a document. I assuem this is correct.

I was wondering if you planing to add any persistence ? like using it with tailor.

I ask because we are building various flutter components and one if a Rich Text Document writer, and Searching through many of the docs to find text is one of our needs.

We use HIVE and will persist the documents in HIVE.

---

The other way is to just search the documents everytime and not maintain an index. Will get slower as more docs are added.

thanks for the amazing high quality libs btw !!!

**Comment by AKushWarrior** [comment]
Done in v0.2.1. Will upload to Github in a minute.

**Comment by AKushWarrior** [comment]
On both Github and Pub now. Tell me if you have any issues.

**Comment by AKushWarrior** [comment]
@MisterJimson I think you'd also expressed interest, so this is a notification.
