### ISSUE TITLE
Issue when installing

### ISSUE THREAD

**Issue by dekadevelop** [AKushWarrior/autotrie#2]
Because autotrie >=0.3.1 depends on collection ^1.14.12 and every version of flutter_localizations from sdk depends on collection 1.14.11, autotrie >=0.3.1 is incompatible with flutter_localizations from sdk.

So, because . depends on both flutter_localizations any from sdk and autotrie ^0.3.1, version solving failed.
pub get failed (1; So, because . depends on both flutter_localizations any from sdk and autotrie ^0.3.1, version solving failed.)

**Comment by AKushWarrior** [comment]
How did you end up fixing it?

**Comment by dekadevelop** [comment]
Sorry I thought I did, but I got the same error again, I'm trying to switch to the dev flutter channel

**Comment by AKushWarrior** [comment]
Don't do that. I don't need the absolute latest collection, I'll just decrease the version constraint.

**Comment by dekadevelop** [comment]
oh ok, thank you :)

**Comment by AKushWarrior** [comment]
Fixed as of v0.3.1+1. If anything else pops up, let me know.
