### ISSUE TITLE
Is autotrie 1.0.0+1 on dev-channel?

### ISSUE THREAD

**Issue by InfiniteTabs** [AKushWarrior/autotrie#4]
Hi,

I'm facing an issue when using the 1.0.0+1 version of autotrie, could it be that the package expects the dev-channel of flutter?

It works perfectly when removing the version 1.0.0+1, but then it installs version 0.4.1.

```
[testautotrie] flutter pub get
Running "flutter pub get" in testautotrie...                    
Because every version of flutter_test from sdk depends on meta 1.1.8 and testautotrie depends on meta ^1.2.2, flutter_test from sdk is forbidden.

So, because testautotrie depends on flutter_test any from sdk, version solving failed.
pub get failed (1; So, because testautotrie depends on flutter_test any from sdk, version solving failed.)
exit code 1
```

I'm using the latest version `Flutter 1.20.2`

**Steps to recreate this:**

```
mkdir testautotrie
cd testautotrie
flutter create .
```

Add `autotrie 1.0.0+1` to the pubspec.yaml file

Best regards

**Comment by AKushWarrior** [comment]
> Hi,
> 
> I'm facing an issue when using the 1.0.0+1 version of autotrie, could it be that the package expects the dev-channel of flutter?
> 
> It works perfectly when removing the version 1.0.0+1, but then it installs version 0.4.1.
> 
> ```
> [testautotrie] flutter pub get
> Running "flutter pub get" in testautotrie...                    
> Because every version of flutter_test from sdk depends on meta 1.1.8 and testautotrie depends on meta ^1.2.2, flutter_test from sdk is forbidden.
> 
> So, because testautotrie depends on flutter_test any from sdk, version solving failed.
> pub get failed (1; So, because testautotrie depends on flutter_test any from sdk, version solving failed.)
> exit code 1
> ```
> 
> I'm using the latest version `Flutter 1.20.2`
> 
> **Steps to recreate this:**
> 
> ```
> mkdir testautotrie
> cd testautotrie
> flutter create .
> ```
> 
> Add `autotrie 1.0.0+1` to the pubspec.yaml file
> 
> Best regards

The issue is that Flutter uses meta version 1.1.8, and I depended on 1.2.2. I'll fix this later today.

**Comment by AKushWarrior** [comment]
Done with the latest commit and https://pub.dev publish.
